<a href="https://colab.research.google.com/github/sflmnt/Business-Intelligence/blob/main/Reto5_Sof%C3%ADa_Lomanto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Reto 5: Sofía Lomanto Salazar**

0. Se procede con la Instalación de los paquetes de trabajo

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import nltk #Natural Language Toolkit
from nltk.tokenize import word_tokenize, sent_tokenize
nltk.download('punkt_tab')  #Para hacer el proceso más eficiente

from google.colab import drive
drive.mount('/content/drive')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# **Análisis de Sentimientos**

0. Se procede con la instalación de las librerias de análisis

In [ ]:
!pip install vaderSentiment                    #Diccionario de trabajo
!pip install -U spacy                          #Es otro diccionar Updated
!pip install -U spacy download es_core_news_lg          #Diccionario en Español
!pip install download en_core_web_sm           #Diccionario en Inglés
!pip install translate                         #Traducción automática
!pip install wordcloud                         #Gráficos de nube de palabras

Requirement already satisfied: vaderSentiment in /usr/local/lib/python3.11/dist-packages (3.3.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from vaderSentiment) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->vaderSentiment) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->vaderSentiment) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->vaderSentiment) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->vaderSentiment) (2025.1.31)
Requirement already satisfied: spacy in /usr/local/lib/python3.11/dist-packages (3.8.5)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.11/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (1.0.12)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy) (3.0.9)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.11/dist-packages (from spacy) (8.3.4)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.11/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.11/dist-packages (from spacy) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.11/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (0.15.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.11/dist-packages (from spacy) (2.11.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (24.2)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (3.5.0)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.11/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.33.0)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.13.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.1.31)
Requirement already satisfied: blis<1.3.0,>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.2.1)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.11/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from weasel<0.5.0,>=0.1.0->spacy) (0.21.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.11/dist-packages (from weasel<0.5.0,>=0.1.0->spacy) (7.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->spacy) (3.0.2)
Requirement already satisfied: marisa-trie>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy) (1.2.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.18.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy) (1.17.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: spacy in /usr/local/lib/python3.11/dist-packages (3.8.5)
Requirement already satisfied: download in /usr/local/lib/python3.11/dist-packages (0.3.5)
ERROR: Could not find a version that satisfies the requirement es_core_news_lg (from versions: none)
ERROR: No matching distribution found for es_core_news_lg
Requirement already satisfied: download in /usr/local/lib/python3.11/dist-packages (0.3.5)
Requirement already satisfied: en_core_web_sm in /usr/local/lib/python3.11/dist-packages (3.8.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from download) (4.67.1)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from download) (1.17.0)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from download) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->download) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->download) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->download) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->download) (2025.1.31)
Requirement already satisfied: translate in /usr/local/lib/python3.11/dist-packages (3.6.1)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from translate) (8.1.8)
Requirement already satisfied: lxml in /usr/local/lib/python3.11/dist-packages (from translate) (5.3.1)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from translate) (2.32.3)
Requirement already satisfied: libretranslatepy==2.1.1 in /usr/local/lib/python3.11/dist-packages (from translate) (2.1.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->translate) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->translate) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->translate) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->translate) (2025.1.31)
Requirement already satisfied: wordcloud in /usr/local/lib/python3.11/dist-packages (1.9.4)
Requirement already satisfied: numpy>=1.6.1 in /usr/local/lib/python3.11/dist-packages (from wordcloud) (2.0.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.11/dist-packages (from wordcloud) (11.1.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from wordcloud) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->wordcloud) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->wordcloud) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->wordcloud) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->wordcloud) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->wordcloud) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->wordcloud) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib->wordcloud) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.17.0)

1. Se cargan las librerias de trabajo

In [ ]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import spacy
from translate import Translator
from wordcloud import WordCloud

# **Análisis Texto Completo 2021**

In [ ]:
import nltk #Natural Language Toolkit
from nltk.tokenize import word_tokenize, sent_tokenize

nxl2021="/content/drive/MyDrive/Análitica 2025-1/InformeJuntaDirectiva_2021 - EN.txt"
ntx2021=open(nxl2021,'r').read()

sent_tokenizer=sent_tokenize(ntx2021)
#Se procede con la clasificación de los sentimientos en la escala PANAS-t
pnst=np.array([-1,-0.8,-0.6,-0.4,-0.2,0,0.2,0.4,0.6,0.8,1.0])
nd=np.zeros((11,1))  #Cuantas sentences nos quedan por cada categoría del panas-t

sia = SentimentIntensityAnalyzer() # Creating an instance of SentimentIntensityAnalyzer
resultados=[]
vs= ['Amenaza','Pesimismo','Inestabilidad','Escepticismo','Indiferente',
          'Neutral','Favorable','Optimismo','Convicción','Consolidado','Confianza']

for sentence in sent_tokenizer:
  scores=sia.polarity_scores(sentence)
  print(sentence,scores['compound'])
  d=np.abs(pnst-scores['compound'])
  print("Las distancias son:\n",d)
  cat=np.where(d==np.min(d))[0][0]
  print("La categoría a la que pertenece es:",cat)
  nd[cat]=nd[cat]+1  #Va contando uno a medida que se van clasificando los datos
  resultados.append([sentence,scores['compound'],vs[cat]])

df=pd.DataFrame(resultados,columns=['Frase','Compound','Sentimiento'])
df.to_excel("Sentimientos_JuntaD2021.xlsx")
df.head()

ANDI presented its 2021 economic overview and 2022 outlook
eco 2022
PreviousNext

Share
2021 ended with an economy that registered significant growth despite the pandemic. 0.6808
Las distancias son:
 [1.6808 1.4808 1.2808 1.0808 0.8808 0.6808 0.4808 0.2808 0.0808 0.1192
 0.3192]
La categoría a la que pertenece es: 8
However, we must continue moving toward recovery: increasing formal employment, promoting an increase in "Inclusive Productivity" in investment, and reactivation. 0.5859
Las distancias son:
 [1.5859 1.3859 1.1859 0.9859 0.7859 0.5859 0.3859 0.1859 0.0141 0.2141
 0.4141]
La categoría a la que pertenece es: 8
Hopefully, this situation will be an opportunity to make decisions that are still pending for our economy. 0.6705
Las distancias son:
 [1.6705 1.4705 1.2705 1.0705 0.8705 0.6705 0.4705 0.2705 0.0705 0.1295
 0.3295]
La categoría a la que pertenece es: 8
2021 Overview and 2022 Outlook

The last two years show a rupture in economic history. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
We talked about economic cycles, trends that strengthened or reversed, or referenced temporary crises around the world. 0.4215
Las distancias son:
 [1.4215 1.2215 1.0215 0.8215 0.6215 0.4215 0.2215 0.0215 0.1785 0.3785
 0.5785]
La categoría a la que pertenece es: 7
The challenge was to be productive, inclusive, and competitive, to integrate into global value chains, and to adapt to the fourth industrial revolution. 0.5267
Las distancias son:
 [1.5267 1.3267 1.1267 0.9267 0.7267 0.5267 0.3267 0.1267 0.0733 0.2733
 0.4733]
La categoría a la que pertenece es: 8
The scope went beyond the economic to social, environmental, and human rights issues. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
These remain priorities. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
However, it is clear that new conditions must be addressed, and one example has been the pandemic, which can be considered a turning point, including its economic dimension. 0.3818
Las distancias son:
 [1.3818 1.1818 0.9818 0.7818 0.5818 0.3818 0.1818 0.0182 0.2182 0.4182
 0.6182]
La categoría a la que pertenece es: 7
Given this scenario, how will 2021 be characterized? 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
One possibility would be to talk about a new normal, a reconfiguration of global value chains, the perfect storm, or the digitalization of the economy. 0.7269
Las distancias son:
 [1.7269 1.5269 1.3269 1.1269 0.9269 0.7269 0.5269 0.3269 0.1269 0.0731
 0.2731]
La categoría a la que pertenece es: 9
But fortunately, 2021 has also been the year of recovery. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
The world managed to overcome an economic contraction of -3.1% to place itself on a path of high growth (5.9%), where dynamism has been greater than expected. 0.7717
Las distancias son:
 [1.7717 1.5717 1.3717 1.1717 0.9717 0.7717 0.5717 0.3717 0.1717 0.0283
 0.2283]
La categoría a la que pertenece es: 9
In Colombia, the recovery was evident with one of the highest growth rates in the region. 0.3818
Las distancias son:
 [1.3818 1.1818 0.9818 0.7818 0.5818 0.3818 0.1818 0.0182 0.2182 0.4182
 0.6182]
La categoría a la que pertenece es: 7
Economic Facts

The global economy is framed by three events: a public health environment, the disruption of supply chains, and economic stimulus in the recovery. -0.3612
Las distancias son:
 [0.6388 0.4388 0.2388 0.0388 0.1612 0.3612 0.5612 0.7612 0.9612 1.1612
 1.3612]
La categoría a la que pertenece es: 3
2020 saw significant loss of life. -0.128
Las distancias son:
 [0.872 0.672 0.472 0.272 0.072 0.128 0.328 0.528 0.728 0.928 1.128]
La categoría a la que pertenece es: 4
In 2021, the vaccination strategy has been the focus, taking into account new variants and the need to adjust health systems and financial sustainability due to health conditions. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
International trade achieved dynamism that exceeded expectations. 0.3818
Las distancias son:
 [1.3818 1.1818 0.9818 0.7818 0.5818 0.3818 0.1818 0.0182 0.2182 0.4182
 0.6182]
La categoría a la que pertenece es: 7
Restrictions on raw materials, shortages of semiconductors, energy resources, and containers are evident, and trade volumes have been insufficient to meet demand. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
Shipping companies have also lacked availability and port infrastructure had adjusted to the 2020 situation. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
The result of 2021 is global inflation, rising freight and logistics costs, and shortages of intermediate inputs and final goods. -0.1531
Las distancias son:
 [0.8469 0.6469 0.4469 0.2469 0.0469 0.1531 0.3531 0.5531 0.7531 0.9531
 1.1531]
La categoría a la que pertenece es: 4
Many forces are converging toward increasing inflationary pressure. -0.296
Las distancias son:
 [0.704 0.504 0.304 0.104 0.096 0.296 0.496 0.696 0.896 1.096 1.296]
La categoría a la que pertenece es: 4
It is important to recognize this when defining the public policy that, as a country, must adopt to address inflation. 0.3612
Las distancias son:
 [1.3612 1.1612 0.9612 0.7612 0.5612 0.3612 0.1612 0.0388 0.2388 0.4388
 0.6388]
La categoría a la que pertenece es: 7
Facing domestic price increases is not the same as facing global situations. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
Governments have responded to this. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
The economic policy mix has been an expansionary monetary policy accompanied by economic support for households and assistance for businesses to avoid closures. 0.128
Las distancias son:
 [1.128 0.928 0.728 0.528 0.328 0.128 0.072 0.272 0.472 0.672 0.872]
La categoría a la que pertenece es: 6
This was primarily the case in 2020, and many have suspended it for 2021. -0.4767
Las distancias son:
 [0.5233 0.3233 0.1233 0.0767 0.2767 0.4767 0.6767 0.8767 1.0767 1.2767
 1.4767]
La categoría a la que pertenece es: 3
Recently, monetary policy, as an initial measure to control inflation, has seen rates rise. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
In Colombia, the health challenges, raw material restrictions, and inflationary pressures are being replicated, with the government responding with aid to the population and the monetary authority adjusting its policies to market conditions. -0.1779
Las distancias son:
 [0.8221 0.6221 0.4221 0.2221 0.0221 0.1779 0.3779 0.5779 0.7779 0.9779
 1.1779]
La categoría a la que pertenece es: 4
We cannot forget the effects of the national strike on the productive apparatus and the logistics and trade structure. 0.0428
Las distancias son:
 [1.0428 0.8428 0.6428 0.4428 0.2428 0.0428 0.1572 0.3572 0.5572 0.7572
 0.9572]
La categoría a la que pertenece es: 5
The country's growth in 2021 is reflected in several sectors and, from a spending perspective, is positive: consumption is driving the economy, reflecting an improvement in households; investment is growing, indicating business confidence in the country; and industrial exports are recording their highest growth in almost a decade. 0.9413
Las distancias son:
 [1.9413 1.7413 1.5413 1.3413 1.1413 0.9413 0.7413 0.5413 0.3413 0.1413
 0.0587]
La categoría a la que pertenece es: 10
This is a clear transition toward recovery. 0.3818
Las distancias son:
 [1.3818 1.1818 0.9818 0.7818 0.5818 0.3818 0.1818 0.0182 0.2182 0.4182
 0.6182]
La categoría a la que pertenece es: 7
The role of the business community was overwhelming. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
Over these two years, the business community, beyond maintaining its activity in an environment of confinement, uncertainty, and depressed markets, has been characterized by a supportive attitude and a deep awareness of society's needs. -0.5423
Las distancias son:
 [0.4577 0.2577 0.0577 0.1423 0.3423 0.5423 0.7423 0.9423 1.1423 1.3423
 1.5423]
La categoría a la que pertenece es: 2
During the discussions surrounding tax reform, they asked the government and Congress not to affect those hit hard by the pandemic and invited business owners to address the country's significant fiscal needs through corporate taxes. 0.1027
Las distancias son:
 [1.1027 0.9027 0.7027 0.5027 0.3027 0.1027 0.0973 0.2973 0.4973 0.6973
 0.8973]
La categoría a la que pertenece es: 6
At the negotiation table, an agreement was reached raising the minimum wage to $1,000,000, as well as the transportation assistance to 10.07%. 0.6908
Las distancias son:
 [1.6908 1.4908 1.2908 1.0908 0.8908 0.6908 0.4908 0.2908 0.0908 0.1092
 0.3092]
La categoría a la que pertenece es: 8
This was accompanied by the need to protect workers, communities, and their families, by purchasing 2,100,000 doses of COVID vaccines, complementing the national plan. 0.3818
Las distancias son:
 [1.3818 1.1818 0.9818 0.7818 0.5818 0.3818 0.1818 0.0182 0.2182 0.4182
 0.6182]
La categoría a la que pertenece es: 7
to the government's vaccination program. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
Thus, the business community continues to invest in the country, always seeking the well-being of Colombians. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
The Challenges Ahead

The pandemic exacerbated the Colombian economy's existing difficulties. -0.2263
Las distancias son:
 [0.7737 0.5737 0.3737 0.1737 0.0263 0.2263 0.4263 0.6263 0.8263 1.0263
 1.2263]
La categoría a la que pertenece es: 4
Unemployment is in double digits. -0.4404
Las distancias son:
 [0.5596 0.3596 0.1596 0.0404 0.2404 0.4404 0.6404 0.8404 1.0404 1.2404
 1.4404]
La categoría a la que pertenece es: 3
The challenge is to create formal jobs and train personnel for new production needs. 0.34
Las distancias son:
 [1.34 1.14 0.94 0.74 0.54 0.34 0.14 0.06 0.26 0.46 0.66]
La categoría a la que pertenece es: 7
The government responded to the situation with a fiscal package that raised the deficit to levels above 7% of GDP. -0.4019
Las distancias son:
 [0.5981 0.3981 0.1981 0.0019 0.2019 0.4019 0.6019 0.8019 1.0019 1.2019
 1.4019]
La categoría a la que pertenece es: 3
Another major challenge would be the soundness and sustainability of public finances. 0.1513
Las distancias son:
 [1.1513 0.9513 0.7513 0.5513 0.3513 0.1513 0.0487 0.2487 0.4487 0.6487
 0.8487]
La categoría a la que pertenece es: 6
Looking ahead, the need to align economic policy measures with those associated with the health sector will continue to be a critical issue. -0.3182
Las distancias son:
 [0.6818 0.4818 0.2818 0.0818 0.1182 0.3182 0.5182 0.7182 0.9182 1.1182
 1.3182]
La categoría a la que pertenece es: 3
The digital transformation remains as a legacy. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
E-government has intensified, and procedures are increasingly digital, workers have adjusted to teleworking, virtual education has been introduced, and the business community has become digital and has come to recognize the importance of Big Data and the need for real-time indicators for decision-making. 0.3612
Las distancias son:
 [1.3612 1.1612 0.9612 0.7612 0.5612 0.3612 0.1612 0.0388 0.2388 0.4388
 0.6388]
La categoría a la que pertenece es: 7
Shock policies must be maintained to strengthen recovery and translate into job creation for economic and social development. 0.2023
Las distancias son:
 [1.2023 1.0023 0.8023 0.6023 0.4023 0.2023 0.0023 0.1977 0.3977 0.5977
 0.7977]
La categoría a la que pertenece es: 6
The goal cannot simply be a short-term objective. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
2022 must be the year in which a path is defined for structural reforms: pensions, labor, capital markets, justice, and a tax system that promotes formality, along with a law that clarifies land ownership and use, and a regulatory system for prior consultations with clarity and transparency. 0.8555
Las distancias son:
 [1.8555 1.6555 1.4555 1.2555 1.0555 0.8555 0.6555 0.4555 0.2555 0.0555
 0.1445]
La categoría a la que pertenece es: 9
It will probably be impossible to advance these reforms in one year, but a mechanism for discussing them and a timeline for processing them must be agreed upon. 0.3919
Las distancias son:
 [1.3919 1.1919 0.9919 0.7919 0.5919 0.3919 0.1919 0.0081 0.2081 0.4081
 0.6081]
La categoría a la que pertenece es: 7
We must resume the path toward greater productivity and competitiveness. 0.3612
Las distancias son:
 [1.3612 1.1612 0.9612 0.7612 0.5612 0.3612 0.1612 0.0388 0.2388 0.4388
 0.6388]
La categoría a la que pertenece es: 7
We must consider the new values ​​demanded by consumers and the new paradigms of competitiveness: human rights, environmental sustainability, decent work, the elimination of child labor, and digital transformation. 0.4019
Las distancias son:
 [1.4019 1.2019 1.0019 0.8019 0.6019 0.4019 0.2019 0.0019 0.1981 0.3981
 0.5981]
La categoría a la que pertenece es: 7
Colombia's Great Opportunity

The global need to reduce its carbon footprint presents a new opportunity for Colombia's competitiveness in international markets. 0.8658
Las distancias son:
 [1.8658 1.6658 1.4658 1.2658 1.0658 0.8658 0.6658 0.4658 0.2658 0.0658
 0.1342]
La categoría a la que pertenece es: 9
The low carbon footprint of our energy matrix and our geoeconomic position is undoubtedly a great opportunity to attract investment to the economy. 0.8555
Las distancias son:
 [1.8555 1.6555 1.4555 1.2555 1.0555 0.8555 0.6555 0.4555 0.2555 0.0555
 0.1445]
La categoría a la que pertenece es: 9
In this regard, the country is not starting from scratch: it has natural competitive advantages, it is already developing a strategy to reduce its carbon footprint, the path toward energy reconversion is a reality, and business leaders are incorporating sustainability issues into their strategy. 0.7783
Las distancias son:
 [1.7783 1.5783 1.3783 1.1783 0.9783 0.7783 0.5783 0.3783 0.1783 0.0217
 0.2217]
La categoría a la que pertenece es: 9
If a company wants to reduce its carbon footprint, if it wants to be sustainable, it should locate in locations that allow it to do so. 0.2263
Las distancias son:
 [1.2263 1.0263 0.8263 0.6263 0.4263 0.2263 0.0263 0.1737 0.3737 0.5737
 0.7737]
La categoría a la que pertenece es: 6
Energy is a large part of the strategy, and therefore, it must be located in Colombia. 0.2732
Las distancias son:
 [1.2732 1.0732 0.8732 0.6732 0.4732 0.2732 0.0732 0.1268 0.3268 0.5268
 0.7268]
La categoría a la que pertenece es: 6
Thus, its production will be carried out with lower-emission processes, the geographic location will mean shorter distances traveled to access international ports, cargo and personnel will be able to use electric mobility, and public policy will be aligned with the sustainability objective. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5

                                               Frase  Compound Sentimiento
0  ANDI presented its 2021 economic overview and ...    0.6808  Convicción
1  However, we must continue moving toward recove...    0.5859  Convicción
2  Hopefully, this situation will be an opportuni...    0.6705  Convicción
3  2021 Overview and 2022 Outlook\n\nThe last two...    0.0000     Neutral
4  We talked about economic cycles, trends that s...    0.4215   Optimismo

# **Análisis Texto Completo 2022**

In [ ]:
import nltk #Natural Language Toolkit
from nltk.tokenize import word_tokenize, sent_tokenize

nxl2022="/content/drive/MyDrive/Análitica 2025-1/InformeJuntaDirectiva_2022 - EN.txt"
ntx2022=open(nxl2022,'r').read()

sent_tokenizer=sent_tokenize(ntx2022)

#Se procede con la clasificación de los sentimientos en la escala PANAS-t
pnst=np.array([-1,-0.8,-0.6,-0.4,-0.2,0,0.2,0.4,0.6,0.8,1.0])
nd=np.zeros((11,1))  #Cuantas sentences nos quedan por cada categoría del panas-t

sia = SentimentIntensityAnalyzer() # Creating an instance of SentimentIntensityAnalyzer
resultados=[]
vs= ['Amenaza','Pesimismo','Inestabilidad','Escepticismo','Indiferente',
          'Neutral','Favorable','Optimismo','Convicción','Consolidado','Confianza']

for sentence in sent_tokenizer:
  scores=sia.polarity_scores(sentence)
  print(sentence,scores['compound'])
  d=np.abs(pnst-scores['compound'])
  print("Las distancias son:\n",d)
  cat=np.where(d==np.min(d))[0][0]
  print("La categoría a la que pertenece es:",cat)
  nd[cat]=nd[cat]+1  #Va contando uno a medida que se van clasificando los datos
  resultados.append([sentence,scores['compound'],vs[cat]])

df=pd.DataFrame(resultados,columns=['Frase','Compound','Sentimiento'])
df.to_excel("Sentimientos_JuntaD2022.xlsx")
df.head()

The Colombian Economy's Performance in 2022
Picture of ISAI DAVID CONTRERAS ANIBAL
ISAI DAVID CONTRERAS ANIBAL
March 4, 2024
2 comments

Total views:
1,116

The Colombian economy in 2022 was bittersweet. -0.0772
Las distancias son:
 [0.9228 0.7228 0.5228 0.3228 0.1228 0.0772 0.2772 0.4772 0.6772 0.8772
 1.0772]
La categoría a la que pertenece es: 5
This is because, despite the improvement in growth that occurred during this period, the expected results were not achieved. 0.031
Las distancias son:
 [1.031 0.831 0.631 0.431 0.231 0.031 0.169 0.369 0.569 0.769 0.969]
La categoría a la que pertenece es: 5
That year, its growth was less than desired. 0.5302
Las distancias son:
 [1.5302 1.3302 1.1302 0.9302 0.7302 0.5302 0.3302 0.1302 0.0698 0.2698
 0.4698]
La categoría a la que pertenece es: 8
It was expected not to exceed the limits, but it was too little to achieve the benefits that Colombia would expect upon achieving these results. 0.5267
Las distancias son:
 [1.5267 1.3267 1.1267 0.9267 0.7267 0.5267 0.3267 0.1267 0.0733 0.2733
 0.4733]
La categoría a la que pertenece es: 8
The GDP (Gross Domestic Product) was estimated to have grown during the year, but many economic sectors also experienced declines. -0.2617
Las distancias son:
 [0.7383 0.5383 0.3383 0.1383 0.0617 0.2617 0.4617 0.6617 0.8617 1.0617
 1.2617]
La categoría a la que pertenece es: 4
Entities such as DANE (National Administrative Department of Statistics), MHCP (Ministry of Finance and Public Credit), BRC (Bank of the Republic of Colombia), the government, and others conducted a very detailed quarterly analysis of the country's various sectors, including the economy. 0.3818
Las distancias son:
 [1.3818 1.1818 0.9818 0.7818 0.5818 0.3818 0.1818 0.0182 0.2182 0.4182
 0.6182]
La categoría a la que pertenece es: 7
The statistics obtained for the country's economic sector for 2022 are not entirely negative, but neither are they entirely positive. 0.815
Las distancias son:
 [1.815 1.615 1.415 1.215 1.015 0.815 0.615 0.415 0.215 0.015 0.185]
La categoría a la que pertenece es: 9
EL PAIS América Colombia published the following in an informative article:

Colombia's National Administrative Department of Statistics (DANE) revealed the official growth figure for the country's Gross Domestic Product: 7.5%. -0.128
Las distancias son:
 [0.872 0.672 0.472 0.272 0.072 0.128 0.328 0.528 0.728 0.928 1.128]
La categoría a la que pertenece es: 4
The figure, very positive in typical economic contexts, is bittersweet. 0.5563
Las distancias son:
 [1.5563 1.3563 1.1563 0.9563 0.7563 0.5563 0.3563 0.1563 0.0437 0.2437
 0.4437]
La categoría a la que pertenece es: 8
Bitter because the Ministry of Finance estimated growth of 8.2% and the Bank of the Republic estimated 8.1%, so the increase was lower than expected. 0.046
Las distancias son:
 [1.046 0.846 0.646 0.446 0.246 0.046 0.154 0.354 0.554 0.754 0.954]
La categoría a la que pertenece es: 5
This is a sweet spot because one of the government's and experts' major concerns was excessive growth in 2022 that would lead to stagnation in 2023, and a more moderate pace last year could mean a less severe slowdown this year. 0.5095
Las distancias son:
 [1.5095 1.3095 1.1095 0.9095 0.7095 0.5095 0.3095 0.1095 0.0905 0.2905
 0.4905]
La categoría a la que pertenece es: 8
In another context, it can be seen that Colombia was also economically affected by a global economic phenomenon, inflation, that year; since 2021, there had been a shift in the consumer price index (CPI), due to the supply impacts left by the pandemic. -0.1531
Las distancias son:
 [0.8469 0.6469 0.4469 0.2469 0.0469 0.1531 0.3531 0.5531 0.7531 0.9531
 1.1531]
La categoría a la que pertenece es: 4
What the Colombian markets envisioned was that the year would close with inflation of approximately 12.5%, and that next year it would remain at a high level, close to 7%. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
Although the expected results were not achieved that year, it was confirmed that a very significant level of economic growth was achieved throughout the Latin American region. 0.5709
Las distancias son:
 [1.5709 1.3709 1.1709 0.9709 0.7709 0.5709 0.3709 0.1709 0.0291 0.2291
 0.4291]
La categoría a la que pertenece es: 8
This was due to the figure published by DANE, which concluded that the economy grew 7.5% at the end of 2022. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
This means that more than $1.4 trillion pesos in goods and services were produced. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
Undoubtedly, the factors that enabled this significant growth were:

Wholesale and retail trade. 0.5574
Las distancias son:
 [1.5574 1.3574 1.1574 0.9574 0.7574 0.5574 0.3574 0.1574 0.0426 0.2426
 0.4426]
La categoría a la que pertenece es: 8
Air and ground transportation. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
Accommodation and food services. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
All of these strongly influenced the Colombian economy, but in this context, the category that made the greatest contribution was the manufacturing industry, especially the textile sector, which was one of the largest drivers of employment in Colombia. 0.81
Las distancias son:
 [1.81 1.61 1.41 1.21 1.01 0.81 0.61 0.41 0.21 0.01 0.19]
La categoría a la que pertenece es: 9
Other influential factors in the fourth quarter of the year were:

Entertainment. 0.6908
Las distancias son:
 [1.6908 1.4908 1.2908 1.0908 0.8908 0.6908 0.4908 0.2908 0.0908 0.1092
 0.3092]
La categoría a la que pertenece es: 8
Concerts. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
The World Cup. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
Gaming and gambling. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
It is worth noting that the second quarter of 2022 was the most dynamic for the economy, especially between April and May, continuing until August. 0.5849
Las distancias son:
 [1.5849 1.3849 1.1849 0.9849 0.7849 0.5849 0.3849 0.1849 0.0151 0.2151
 0.4151]
La categoría a la que pertenece es: 8
By September, the economy began to show signs of slowing. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
According to DANE (National Statistics Institute), agriculture, which has maintained a negative trend in recent years, and mining were the most affected sectors during 2022. -0.6801
Las distancias son:
 [0.3199 0.1199 0.0801 0.2801 0.4801 0.6801 0.8801 1.0801 1.2801 1.4801
 1.6801]
La categoría a la que pertenece es: 2
Household spending was one of the main factors driving and driving the economy, ahead of public spending. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
All of this represents progress in Colombia's economic growth, as in years prior to 2022, growth was approximately 3.2%. 0.7906
Las distancias son:
 [1.7906 1.5906 1.3906 1.1906 0.9906 0.7906 0.5906 0.3906 0.1906 0.0094
 0.2094]
La categoría a la que pertenece es: 9
Given the dynamic performance of some sectors in industry, commerce, and the arts, Colombia ranked first in terms of growth among all UN countries. 0.6369
Las distancias son:
 [1.6369 1.4369 1.2369 1.0369 0.8369 0.6369 0.4369 0.2369 0.0369 0.1631
 0.3631]
La categoría a la que pertenece es: 8

                                               Frase  Compound  Sentimiento
0  The Colombian Economy's Performance in 2022\nP...   -0.0772      Neutral
1  This is because, despite the improvement in gr...    0.0310      Neutral
2       That year, its growth was less than desired.    0.5302   Convicción
3  It was expected not to exceed the limits, but ...    0.5267   Convicción
4  The GDP (Gross Domestic Product) was estimated...   -0.2617  Indiferente

# **Análisis Texto Completo 2023**

In [ ]:
import nltk #Natural Language Toolkit
from nltk.tokenize import word_tokenize, sent_tokenize

nxl2023="/content/drive/MyDrive/Análitica 2025-1/InformeJuntaDirectiva_2023 - EN.txt"
ntx2023=open(nxl2023,'r').read()

sent_tokenizer=sent_tokenize(ntx2023)

#Se procede con la clasificación de los sentimientos en la escala PANAS-t
pnst=np.array([-1,-0.8,-0.6,-0.4,-0.2,0,0.2,0.4,0.6,0.8,1.0])
nd=np.zeros((11,1))  #Cuantas sentences nos quedan por cada categoría del panas-t

sia = SentimentIntensityAnalyzer() # Creating an instance of SentimentIntensityAnalyzer
resultados=[]
vs= ['Amenaza','Pesimismo','Inestabilidad','Escepticismo','Indiferente',
          'Neutral','Favorable','Optimismo','Convicción','Consolidado','Confianza']

for sentence in sent_tokenizer:
  scores=sia.polarity_scores(sentence)
  print(sentence,scores['compound'])
  d=np.abs(pnst-scores['compound'])
  print("Las distancias son:\n",d)
  cat=np.where(d==np.min(d))[0][0]
  print("La categoría a la que pertenece es:",cat)
  nd[cat]=nd[cat]+1  #Va contando uno a medida que se van clasificando los datos
  resultados.append([sentence,scores['compound'],vs[cat]])

df=pd.DataFrame(resultados,columns=['Frase','Compound','Sentimiento'])
df.to_excel("Sentimientos_JuntaD2023.xlsx")
df.head()

International Macroeconomic Environment

The global economy expanded at an annual rate of nearly 2.6% in the first quarter of 2023 due to improved consumer confidence, the normalization of global supply chains, and favorable dynamics in services activities. 0.891
Las distancias son:
 [1.891 1.691 1.491 1.291 1.091 0.891 0.691 0.491 0.291 0.091 0.109]
La categoría a la que pertenece es: 9
A slowdown in global growth is anticipated for the remainder of the year amid an uncertain economic climate characterized by geopolitical tensions, risks to financial stability, high debt in many economies, and the effects of restrictive monetary policies in numerous countries, whose inflation rates remain above their targets, despite the declines achieved so far. -0.7096
Las distancias son:
 [0.2904 0.0904 0.1096 0.3096 0.5096 0.7096 0.9096 1.1096 1.3096 1.5096
 1.7096]
La categoría a la que pertenece es: 1
The IMF forecasts that the moderating inflation trend will continue in the coming months, with average annual global inflation falling from 8.7% in 2022 to 6.8% in 2023. -0.1531
Las distancias son:
 [0.8469 0.6469 0.4469 0.2469 0.0469 0.1531 0.3531 0.5531 0.7531 0.9531
 1.1531]
La categoría a la que pertenece es: 4
Economic Activity in Colombia

After achieving strong growth of 7.3% in 2022, GDP growth slowed in the first quarter of 2023, reaching an annualized figure of 3.0%, driven by positive net external demand, primarily due to a drop in imports, especially capital goods, affected by the slowdown in economic activity. 0.8568
Las distancias son:
 [1.8568 1.6568 1.4568 1.2568 1.0568 0.8568 0.6568 0.4568 0.2568 0.0568
 0.1432]
La categoría a la que pertenece es: 9
Domestic demand contributed negatively to growth, reflected in the loss of momentum in household consumption and the contraction of gross capital formation. -0.5106
Las distancias son:
 [0.4894 0.2894 0.0894 0.1106 0.3106 0.5106 0.7106 0.9106 1.1106 1.3106
 1.5106]
La categoría a la que pertenece es: 2
The technical team at the Central Bank forecasts GDP growth of 0.9% in 2023. 0.3818
Las distancias son:
 [1.3818 1.1818 0.9818 0.7818 0.5818 0.3818 0.1818 0.0182 0.2182 0.4182
 0.6182]
La categoría a la que pertenece es: 7
Employment

The unemployment rate continued to decline year-on-year during the first months of 2023, reaching 10.4% in the moving quarter ending in May, below its historical average, largely due to the recovery of employment in rural areas. -0.2732
Las distancias son:
 [0.7268 0.5268 0.3268 0.1268 0.0732 0.2732 0.4732 0.6732 0.8732 1.0732
 1.2732]
La categoría a la que pertenece es: 4
The informality rate stood at 57.3% in May 2023, 0.3 percentage points higher than the 57% observed in December 2022. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
By economic sector, the largest contributions to the annual change in employment, in the national aggregate, were made by the trade and lodging, manufacturing, and professional activities. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
Inflation and Monetary Policy

Consumer price inflation maintained an upward trend throughout the previous year, reaching 13.1% at the end of 2022. 0.2023
Las distancias son:
 [1.2023 1.0023 0.8023 0.6023 0.4023 0.2023 0.0023 0.1977 0.3977 0.5977
 0.7977]
La categoría a la que pertenece es: 6
During the first quarter of 2023, inflation stabilized at around 13.3% annually and began to show a downward trend starting in April, reaching 12.1% annually in June, one percentage point below the level recorded in December 2022. 0.2023
Las distancias son:
 [1.2023 1.0023 0.8023 0.6023 0.4023 0.2023 0.0023 0.1977 0.3977 0.5977
 0.7977]
La categoría a la que pertenece es: 6
The declines in the inflation rate during the second quarter were explained, among other factors, by the drop in food inflation; downward adjustments in international prices for some foods, raw materials, and transportation costs; the appreciation of the exchange rate; and the reduction in producer price inflation, offset by the rise in fuel prices. 0.296
Las distancias son:
 [1.296 1.096 0.896 0.696 0.496 0.296 0.096 0.104 0.304 0.504 0.704]
La categoría a la que pertenece es: 6
Balance of Payments

In the first quarter of 2023, the current account deficit was 4.2% of GDP. -0.4019
Las distancias son:
 [0.5981 0.3981 0.1981 0.0019 0.2019 0.4019 0.6019 0.8019 1.0019 1.2019
 1.4019]
La categoría a la que pertenece es: 3
This meant a reduction in the external imbalance of two percentage points of GDP, compared to that recorded in the same quarter of 2022. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
This decrease was primarily due to the reduction in the goods trade deficit and the lower imbalance in services trade. -0.5994
Las distancias son:
 [4.0060e-01 2.0060e-01 6.0000e-04 1.9940e-01 3.9940e-01 5.9940e-01
 7.9940e-01 9.9940e-01 1.1994e+00 1.3994e+00 1.5994e+00]
La categoría a la que pertenece es: 2
For 2023, the technical team projects a current account deficit of 4.1% of GDP, lower than the 6.2% deficit observed in 2022.

International Reserves

So far in 2023, there has been an increase in the level of net international reserves, which totaled USD 57,705.7 million (m) as of May 31, 2023, representing an increase of USD 436.6 million compared to the amount recorded at the end of 2022. -0.4588
Las distancias son:
 [0.5412 0.3412 0.1412 0.0588 0.2588 0.4588 0.6588 0.8588 1.0588 1.2588
 1.4588]
La categoría a la que pertenece es: 3
This is due to the positive profitability obtained during this period, resulting from the higher returns received. 0.6908
Las distancias son:
 [1.6908 1.4908 1.2908 1.0908 0.8908 0.6908 0.4908 0.2908 0.0908 0.1092
 0.3092]
La categoría a la que pertenece es: 8
The appreciation of investments has also contributed to the increase in the level of reserves. 0.6808
Las distancias son:
 [1.6808 1.4808 1.2808 1.0808 0.8808 0.6808 0.4808 0.2808 0.0808 0.1192
 0.3192]
La categoría a la que pertenece es: 8
These positive impacts on investments have been partially offset by the devaluation of other reserve currencies against the US dollar, which has generated a negative exchange rate effect on the valuation of reserves. -0.0258
Las distancias son:
 [0.9742 0.7742 0.5742 0.3742 0.1742 0.0258 0.2258 0.4258 0.6258 0.8258
 1.0258]
La categoría a la que pertenece es: 5
Bank of the Republic's Earnings

In the first half of 2023, the Bank of the Republic's earnings amounted to COP 4,049 billion (mm), as a result of income of COP 6,423 billion and expenses of COP 2,374 billion. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
Income was mainly due to the return on international reserves and, to a lesser extent, to the return on the TES held by the Bank and on expansionary repos. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
Expenditures are mainly explained by the remuneration of government deposits with the Bank and contractionary deposits, and by current expenses. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
Corporate. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
A profit of COP 8,408 billion is projected for 2023, higher than that obtained in 2022 (COP 1,506 billion), which would come primarily from the return on international reserves. 0.4404
Las distancias son:
 [1.4404 1.2404 1.0404 0.8404 0.6404 0.4404 0.2404 0.0404 0.1596 0.3596
 0.5596]
La categoría a la que pertenece es: 7
The expected return on reserves would respond to high external interest rates. 0.4588
Las distancias son:
 [1.4588 1.2588 1.0588 0.8588 0.6588 0.4588 0.2588 0.0588 0.1412 0.3412
 0.5412]
La categoría a la que pertenece es: 7
Public Finance

The fiscal deficit of the Central National Government (CNG) stood at 5.3% of GDP in 2022, which implied a correction of 1.7 percentage points compared to the 2021 deficit (7.0% of GDP). -0.6597
Las distancias son:
 [0.3403 0.1403 0.0597 0.2597 0.4597 0.6597 0.8597 1.0597 1.2597 1.4597
 1.6597]
La categoría a la que pertenece es: 2
With this result, the CNG achieved the deficit target established for the transition period in the Fiscal Rule (8.3%). -0.4019
Las distancias son:
 [0.5981 0.3981 0.1981 0.0019 0.2019 0.4019 0.6019 0.8019 1.0019 1.2019
 1.4019]
La categoría a la que pertenece es: 3
This adjustment was possible thanks to the dynamism of the Colombian economy, which boosted tax collection, favorable terms of trade, and the reduction of spending pressures associated with the COVID-19 pandemic. 0.8316
Las distancias son:
 [1.8316 1.6316 1.4316 1.2316 1.0316 0.8316 0.6316 0.4316 0.2316 0.0316
 0.1684]
La categoría a la que pertenece es: 9

                                               Frase  Compound    Sentimiento
0  International Macroeconomic Environment\n\nThe...    0.8910    Consolidado
1  A slowdown in global growth is anticipated for...   -0.7096      Pesimismo
2  The IMF forecasts that the moderating inflatio...   -0.1531    Indiferente
3  Economic Activity in Colombia\n\nAfter achievi...    0.8568    Consolidado
4  Domestic demand contributed negatively to grow...   -0.5106  Inestabilidad

# **Análisis Texto Completo 2024**

In [ ]:
import nltk #Natural Language Toolkit
from nltk.tokenize import word_tokenize, sent_tokenize

nxl2024="/content/drive/MyDrive/Análitica 2025-1/InformeJuntaDirectiva_2024 - EN.txt"
ntx2024=open(nxl2024,'r').read()

sent_tokenizer=sent_tokenize(ntx2024)

#Se procede con la clasificación de los sentimientos en la escala PANAS-t
pnst=np.array([-1,-0.8,-0.6,-0.4,-0.2,0,0.2,0.4,0.6,0.8,1.0])
nd=np.zeros((11,1))  #Cuantas sentences nos quedan por cada categoría del panas-t

sia = SentimentIntensityAnalyzer() # Creating an instance of SentimentIntensityAnalyzer
resultados=[]
vs= ['Amenaza','Pesimismo','Inestabilidad','Escepticismo','Indiferente',
          'Neutral','Favorable','Optimismo','Convicción','Consolidado','Confianza']

for sentence in sent_tokenizer:
  scores=sia.polarity_scores(sentence)
  print(sentence,scores['compound'])
  d=np.abs(pnst-scores['compound'])
  print("Las distancias son:\n",d)
  cat=np.where(d==np.min(d))[0][0]
  print("La categoría a la que pertenece es:",cat)
  nd[cat]=nd[cat]+1  #Va contando uno a medida que se van clasificando los datos
  resultados.append([sentence,scores['compound'],vs[cat]])

df=pd.DataFrame(resultados,columns=['Frase','Compound','Sentimiento'])
df.to_excel("Sentimientos_JuntaD2024.xlsx")
df.head()

During the first quarter of 2024, economic activity in Colombia maintained the recovery trend it exhibited in the last quarter of 2023. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
After the 0.7% contraction in gross domestic product (GDP) in the third quarter of 2023, this variable grew by 0.4% in the fourth quarter of last year and 0.9% between January and March of this year. -0.4767
Las distancias son:
 [0.5233 0.3233 0.1233 0.0767 0.2767 0.4767 0.6767 0.8767 1.0767 1.2767
 1.4767]
La categoría a la que pertenece es: 3
Although this growth rate remains moderate, the forecasts of the technical team and various analysts indicate that it will consolidate in the coming months, approaching its potential capacity in 2025. 0.3818
Las distancias son:
 [1.3818 1.1818 0.9818 0.7818 0.5818 0.3818 0.1818 0.0182 0.2182 0.4182
 0.6182]
La categoría a la que pertenece es: 7
Furthermore, the annual inflation rate made progress in its convergence to the target during the first half of the year, declining from 9.3% in December to 7.4% in March, and stabilizing around 7.2% in the second quarter. 0.4215
Las distancias son:
 [1.4215 1.2215 1.0215 0.8215 0.6215 0.4215 0.2215 0.0215 0.1785 0.3785
 0.5785]
La categoría a la que pertenece es: 7
Likewise, the country's external imbalance continued to narrow, with a current account deficit of 1.9% of GDP recorded in the first three months of the year, which was lower than that of 2023 (2.5% of GDP) and that observed in the same period of the previous year (3.7% of GDP). -0.5994
Las distancias son:
 [4.0060e-01 2.0060e-01 6.0000e-04 1.9940e-01 3.9940e-01 5.9940e-01
 7.9940e-01 9.9940e-01 1.1994e+00 1.3994e+00 1.5994e+00]
La categoría a la que pertenece es: 2
Regarding public finances, the significant correction of the fiscal imbalance achieved the previous year stands out, which resulted in a reduction in the General Government deficit from 6.3% to 2.7% of GDP between 2022 and 2023. -0.2263
Las distancias son:
 [0.7737 0.5737 0.3737 0.1737 0.0263 0.2263 0.4263 0.6263 0.8263 1.0263
 1.2263]
La categoría a la que pertenece es: 4
Since December 2023, these macroeconomic advances have been accompanied by the start of a new monetary policy cycle, with progressive interest rate reductions. 0.4588
Las distancias son:
 [1.4588 1.2588 1.0588 0.8588 0.6588 0.4588 0.2588 0.0588 0.1412 0.3412
 0.5412]
La categoría a la que pertenece es: 7
The decision to undertake this policy change stems from the consensus reached among the co-directors of the Board of Directors of the Banco de la República (JDBR) that favorable conditions have been created for adopting a less contractionary policy stance, as confirmed by the downward trend shown by both annual inflation and inflation expectations since April 2023, as well as the correction of the external deficit toward a more sustainable balance. 0.5994
Las distancias son:
 [1.5994e+00 1.3994e+00 1.1994e+00 9.9940e-01 7.9940e-01 5.9940e-01
 3.9940e-01 1.9940e-01 6.0000e-04 2.0060e-01 4.0060e-01]
La categoría a la que pertenece es: 8
While these favorable conditions are identified, some significant risks to inflation's convergence to its 3% target are noted. 0.4215
Las distancias son:
 [1.4215 1.2215 1.0215 0.8215 0.6215 0.4215 0.2215 0.0215 0.1785 0.3785
 0.5785]
La categoría a la que pertenece es: 7
These include the downward rigidity of inflation in some services, including rents and energy rates, as well as the risks of a depreciation of the peso against the dollar due to changing conditions in the external context, the persisting uncertainty regarding monetary policy in the United States, and local public policy issues. 0.2023
Las distancias son:
 [1.2023 1.0023 0.8023 0.6023 0.4023 0.2023 0.0023 0.1977 0.3977 0.5977
 0.7977]
La categoría a la que pertenece es: 6
Likewise, there is the risk related to food prices, whose inflation spiked in May and June due to the effects of the El Niño phenomenon on the harvests of certain perishable foods. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
Additionally, while inflation expectations show a downward trend over time, they remain above the target for the relevant timeframes in which the Board of Directors (BDBR) aims to achieve it. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5
Furthermore, the expected increase in the Central National Government (CNG) deficit in 2024 could make it difficult for inflation to converge toward its target within the timeframe in which the Board of Directors (BDBR) hopes to achieve it. -0.0258
Las distancias son:
 [0.9742 0.7742 0.5742 0.3742 0.1742 0.0258 0.2258 0.4258 0.6258 0.8258
 1.0258]
La categoría a la que pertenece es: 5
The existence of the aforementioned risks to inflation behavior requires the monetary authority to be especially cautious with the amount of policy interest rate cuts. -0.1761
Las distancias son:
 [0.8239 0.6239 0.4239 0.2239 0.0239 0.1761 0.3761 0.5761 0.7761 0.9761
 1.1761]
La categoría a la que pertenece es: 4
This is because there is a risk that very rapid declines may have to be reversed, at significant credibility costs, if events materialize that make it difficult to achieve the inflation target within the timeframes set by the Board of Directors. -0.4215
Las distancias son:
 [0.5785 0.3785 0.1785 0.0215 0.2215 0.4215 0.6215 0.8215 1.0215 1.2215
 1.4215]
La categoría a la que pertenece es: 3
Hence the importance of each decision using the most recent available information as the basis for a detailed assessment of inflation behavior and expectations; observed and expected economic growth; and other key variables that determine the country's macroeconomic stability and the convergence of inflation toward its target. 0.6249
Las distancias son:
 [1.6249 1.4249 1.2249 1.0249 0.8249 0.6249 0.4249 0.2249 0.0249 0.1751
 0.3751]
La categoría a la que pertenece es: 8
This task is regularly carried out by the technical team of the Banco de la República for each Board of Directors session. 0.0
Las distancias son:
 [1.  0.8 0.6 0.4 0.2 0.  0.2 0.4 0.6 0.8 1. ]
La categoría a la que pertenece es: 5

                                               Frase  Compound    Sentimiento
0  During the first quarter of 2024, economic act...    0.0000        Neutral
1  After the 0.7% contraction in gross domestic p...   -0.4767   Escepticismo
2  Although this growth rate remains moderate, th...    0.3818      Optimismo
3  Furthermore, the annual inflation rate made pr...    0.4215      Optimismo
4  Likewise, the country's external imbalance con...   -0.5994  Inestabilidad